import { EmbedBuilder } from 'discord.js';
import { config } from '../config.js';

const COLORS = {
    pending: 0xFFA500,   // Orange
    approved: 0x2ECC71, // Green
    rejected: 0xE74C3C, // Red
    shipped: 0x9B59B6,  // Purple
    info: 0x3498DB,     // Blue
};

/**
 * Create an embed for a pending submission
 */
export function createPendingEmbed(spec) {
    const appDisplay = spec.appChannelId ? `<#${spec.appChannelId}>` : spec.app;

    const embed = new EmbedBuilder()
        .setColor(COLORS.pending)
        .setTitle(`⏳ ${spec.title}`)
        .setDescription(spec.description || spec.userStory || 'No description provided');

    // Always show these fields
    const fields = [
        { name: '👤 Submitted By', value: spec.submittedBy, inline: true },
        { name: '📱 App', value: appDisplay, inline: true },
    ];

    // Only show reward if enabled in config
    if (config.enableRewards) {
        fields.push({ name: '💰 Reward', value: `${spec.suiteReward} SUITE`, inline: true });
    }

    fields.push({ name: '📁 Type', value: spec.type.toUpperCase(), inline: true });

    embed.addFields(...fields)
        .setFooter({ text: '🚀 IDE | 🔧 Manual | 📋 TODO | 🔍 Info | ❌ Reject' })
        .setTimestamp();

    // Add type-specific fields
    if (spec.type === 'bug') {
        if (spec.severity) {
            embed.addFields({ name: '🔴 Severity', value: spec.severity, inline: true });
        }
        if (spec.stepsToReproduce?.length) {
            embed.addFields({
                name: '📋 Steps to Reproduce',
                value: spec.stepsToReproduce.map((s, i) => `${i + 1}. ${s}`).join('\n')
            });
        }
    } else if (spec.type === 'feature') {
        if (spec.priority) {
            embed.addFields({ name: '⚡ Priority', value: spec.priority, inline: true });
        }
        if (spec.acceptanceCriteria?.length) {
            embed.addFields({
                name: '✓ Acceptance Criteria',
                value: spec.acceptanceCriteria.map(c => `• ${c}`).join('\n')
            });
        }
    } else if (spec.type === 'content') {
        if (spec.platform) {
            embed.addFields({ name: '📱 Platform', value: spec.platform, inline: true });
        }
        if (spec.url) {
            embed.addFields({ name: '🔗 URL', value: spec.url });
        }
    }

    return embed;
}

/**
 * Create an embed for an approved submission
 */
export function createApprovedEmbed(spec, approvedBy) {
    return new EmbedBuilder()
        .setColor(COLORS.approved)
        .setTitle(`✅ ${spec.title}`)
        .setDescription(spec.description || spec.userStory || 'No description')
        .addFields(
            { name: '👤 Submitted By', value: spec.submittedBy, inline: true },
            { name: '✓ Approved By', value: approvedBy, inline: true },
            { name: '💰 Reward', value: `${spec.suiteReward} SUITE`, inline: true }
        )
        .setTimestamp();
}

/**
 * Create an embed for a shipped item
 */
export function createShippedEmbed(spec, shippedBy) {
    return new EmbedBuilder()
        .setColor(COLORS.shipped)
        .setTitle(`🚀 ${spec.title}`)
        .setDescription(`This ${spec.type} has been shipped!`)
        .addFields(
            { name: '👤 Contributor', value: spec.submittedBy, inline: true },
            { name: '🚀 Shipped By', value: shippedBy, inline: true },
            { name: '💰 Total Reward', value: `${spec.suiteReward} SUITE`, inline: true }
        )
        .setTimestamp();
}

/**
 * Create a leaderboard embed
 */
export function createLeaderboardEmbed(leaders) {
    const embed = new EmbedBuilder()
        .setColor(COLORS.info)
        .setTitle('🏆 Weekly Leaderboard')
        .setDescription('Top contributors this week')
        .setTimestamp();

    if (leaders.length === 0) {
        embed.addFields({ name: 'No contributions yet', value: 'Be the first!' });
    } else {
        const medals = ['🥇', '🥈', '🥉'];
        const leaderText = leaders
            .slice(0, 10)
            .map((l, i) => `${medals[i] || `${i + 1}.`} **${l.username}** - ${l.totalSuite} SUITE`)
            .join('\n');
        embed.addFields({ name: 'Rankings', value: leaderText });
    }

    return embed;
}

/**
 * Create an embed for Claude's code review result
 */
export function createCodeReviewEmbed(spec, codeResult, model) {
    const embed = new EmbedBuilder()
        .setColor(model === 'opus' ? 0x9B59B6 : 0x3498DB)  // Purple for Opus, Blue for Sonnet
        .setTitle(`🤖 Code Generated by Claude ${model === 'opus' ? 'Opus' : 'Sonnet'}`)
        .setDescription(codeResult.explanation || 'Code changes generated successfully');

    // Add code blocks (truncated for Discord's 1024 char limit per field)
    if (codeResult.code?.length > 0) {
        const firstBlock = codeResult.code[0];
        const codePreview = firstBlock.code.length > 900
            ? firstBlock.code.substring(0, 900) + '\n... (truncated)'
            : firstBlock.code;

        embed.addFields({
            name: `📝 Code (${firstBlock.language})`,
            value: `\`\`\`${firstBlock.language}\n${codePreview}\n\`\`\``
        });

        if (codeResult.code.length > 1) {
            embed.addFields({
                name: '📂 Additional Files',
                value: `${codeResult.code.length - 1} more file(s) changed`
            });
        }
    }

    embed.setFooter({ text: `React with 🚀 to deploy this code` })
        .setTimestamp();

    return embed;
}
