/**
 * Workout-related type definitions
 */

/**
 * Muscle groups for categorizing exercises
 */
export type MuscleGroup =
    | 'chest'
    | 'back'
    | 'shoulders'
    | 'biceps'
    | 'triceps'
    | 'forearms'
    | 'quadriceps'
    | 'hamstrings'
    | 'glutes'
    | 'calves'
    | 'core'
    | 'lower_back';

/**
 * Exercise equipment types
 */
export type Equipment =
    | 'barbell'
    | 'dumbbell'
    | 'cable'
    | 'machine'
    | 'bodyweight'
    | 'kettlebell'
    | 'resistance_band';

/**
 * Exercise category
 */
export type ExerciseCategory = 'compound' | 'isolation' | 'cardio';

/**
 * Form quality rating
 */
export type FormQuality = 'excellent' | 'good' | 'fair' | 'poor';

/**
 * Session status
 */
export type SessionStatus = 'idle' | 'preparing' | 'active' | 'paused' | 'completed';

/**
 * Workout plan schedule type
 */
export interface PlanSchedule {
    [dayNumber: string]: MuscleGroup[];
}

/**
 * Rep detection configuration for an exercise
 */
export interface RepDetectionConfig {
    angleThresholdUp: number;   // Angle indicating top of movement
    angleThresholdDown: number; // Angle indicating bottom of movement
    minRepDuration?: number;    // Minimum rep duration in ms
    maxRepDuration?: number;    // Maximum rep duration in ms
}

/**
 * Exercise with MediaPipe tracking configuration
 */
export interface ExerciseWithTracking {
    id: string;
    name: string;
    category: ExerciseCategory;
    muscleGroups: MuscleGroup[];
    equipment?: Equipment;
    trackedJoints?: string[];
    repDetectionConfig?: RepDetectionConfig;
}

/**
 * Active set during a workout
 */
export interface ActiveSet {
    exerciseId: string;
    exerciseName: string;
    setNumber: number;
    targetReps?: number;
    weight?: number;
    completedReps: number;
    startedAt: Date;
    repTimestamps: number[]; // Timestamps of each rep
}

/**
 * Session statistics
 */
export interface SessionStats {
    duration: number;      // Seconds
    totalReps: number;
    totalSets: number;
    totalVolume: number;   // lbs
    exerciseCount: number;
}

/**
 * Workout summary generated by AI
 */
export interface WorkoutSummary {
    performanceScore: number; // 1-100
    highlights: string[];
    improvements: string[];
    recommendations: string[];
    formNotes: string[];
}
