-- Agent-built apps table
-- Stores HTML apps generated by AI agents (separate from user_apps which requires auth.users FK)

CREATE TABLE IF NOT EXISTS agent_apps (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    agent_id UUID REFERENCES factory_users(id),
    proposal_id UUID,
    name TEXT NOT NULL,
    slug TEXT,
    description TEXT,
    code TEXT NOT NULL,
    icon_bg TEXT DEFAULT 'linear-gradient(135deg, #6366f1, #8b5cf6)',
    version INTEGER DEFAULT 1,
    is_public BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_apps_agent ON agent_apps(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_apps_slug ON agent_apps(slug);

-- RLS: anyone can read public agent apps, service role can do everything
ALTER TABLE agent_apps ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view public agent apps" ON agent_apps
    FOR SELECT USING (is_public = true);

CREATE POLICY "Service role full access on agent apps" ON agent_apps
    FOR ALL USING (auth.role() = 'service_role');

-- Also add total_tokens_used to factory_users if not exists
ALTER TABLE factory_users ADD COLUMN IF NOT EXISTS total_tokens_used INTEGER DEFAULT 0;
