// LegalDraft API - Legal document generation via Gemini
export default async function handler(req, res) {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') return res.status(200).end();
    if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

    const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
    if (!GEMINI_API_KEY) return res.status(500).json({ error: 'Gemini API key not configured' });

    const { mode, docType, details, question, history } = req.body;

    if (!mode) return res.status(400).json({ error: 'Mode is required' });

    try {
        let systemInstruction, contents;

        if (mode === 'generate') {
            if (!docType || !details) return res.status(400).json({ error: 'Document type and details are required' });

            systemInstruction = `You are an expert legal document drafter. Generate a professional legal document based on the provided details. Return a JSON object with this structure:
{
  "title": "Full document title",
  "subtitle": "Brief description of what this document covers",
  "effectiveDate": "[DATE]",
  "sections": [
    {
      "number": "1",
      "heading": "Section heading",
      "content": "Full section text with proper legal language"
    }
  ],
  "signatures": [
    {
      "role": "Party role (e.g., Disclosing Party)",
      "name": "[NAME]",
      "line": "Signature: _______________"
    }
  ],
  "notes": ["Important note about this document", "When to consult a lawyer"],
  "disclaimer": "This document is a template generated by AI and is not legal advice. Have it reviewed by a qualified attorney before use."
}

Rules:
- Document type: ${docType}
- Use proper legal language and formatting
- Include all standard clauses for this document type
- Use placeholder brackets [BRACKETS] for specific details the user hasn't provided (names, dates, addresses, amounts)
- Fill in details the user HAS provided
- Include standard boilerplate (governing law, severability, entire agreement, amendments)
- Number all sections and subsections clearly
- Make the document comprehensive but not excessively long
- Include signature blocks appropriate for the document type
- Add practical notes about what to customize before signing
- ALWAYS include the disclaimer about not being legal advice
- Return ONLY valid JSON, no markdown fences`;

            const detailText = typeof details === 'string' ? details : Object.entries(details).map(([k, v]) => `${k}: ${v}`).join('\n');
            contents = [{ parts: [{ text: `Generate a ${docType} document with these details:\n\n${detailText}` }] }];

        } else if (mode === 'qa') {
            if (!question) return res.status(400).json({ error: 'Question is required' });

            systemInstruction = `You are a legal document expert. Help the user understand, customize, or improve their legal document. Provide clear explanations in plain language. Always note that your advice is educational and they should consult an attorney for specific legal situations.`;

            const messages = [];
            if (history?.length > 0) {
                for (const msg of history) {
                    messages.push({ role: msg.role === 'user' ? 'user' : 'model', parts: [{ text: msg.content }] });
                }
            }
            messages.push({ parts: [{ text: question }] });
            contents = messages;

        } else {
            return res.status(400).json({ error: 'Invalid mode' });
        }

        const requestBody = {
            contents,
            systemInstruction: { parts: [{ text: systemInstruction }] },
            generationConfig: {
                temperature: mode === 'generate' ? 0.3 : 0.6,
                maxOutputTokens: 8192
            }
        };

        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
            { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(requestBody) }
        );

        const data = await response.json();
        if (!response.ok) return res.status(response.status).json({ error: data.error?.message || 'Gemini API error' });

        const responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || '';

        if (mode === 'qa') {
            return res.status(200).json({ answer: responseText });
        }

        try {
            const cleaned = responseText.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim();
            const parsed = JSON.parse(cleaned);
            return res.status(200).json(parsed);
        } catch (parseError) {
            return res.status(200).json({ raw: responseText });
        }

    } catch (error) {
        console.error('LegalDraft API error:', error);
        return res.status(500).json({ error: 'Failed to generate document' });
    }
}
